# Generated by Django 5.1.3 on 2024-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imgUrl', models.URLField(max_length=1000)),
                ('tags', models.TextField()),
                ('location', models.TextField()),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comments', models.JSONField(default=list)),
            ],
        ),
    ]
