# Generated by Django 5.1.3 on 2024-11-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('imageUrl', models.URLField(max_length=1000)),
                ('following', models.JSONField(default=list)),
                ('followers', models.JSONField(default=list)),
            ],
        ),
    ]
