
# Generated by Django 5.1.3 on 2024-11-15 21:38

# Generated by Django 5.1.3 on 2024-11-15 23:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='user.user'),
        ),
    ]
